language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=1.3.3
    - DJANGO_VERSION=1.4.1
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - pip install -q -r travis.txt --use-mirrors
    - pip install Fabric==1.4.3 --use-mirrors
script: fab test
